kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: prow-subpath
nodes:
- role: control-plane
  image: kindest/node:v1.29.4
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 8888
    hostPort: 8888
    protocol: TCP
  - containerPort: 9000
    hostPort: 9000
    protocol: TCP
